languageCode = "pt-BR"
languageName = "Português"
weight = 2
title = "Tiago Vignatti"

[params]
  displayName = "Português"
  isoCode = "pt-BR"
  dateFormat = "2 de January de 2006"

[author]
  name = ""
  image = "/images/avatar.png"
  headline = "arte - ciência da computação - brincar"
  bio = ""
  links = [
    { github = "https://github.com/tiagovignatti" },
    { instagram = "https://instagram.com/tiagovignatti" },
  ]
